### ISSUE TITLE
(enhancement): use python's logger instead of prints

### ISSUE THREAD

**Issue by aaronkaplan** [EC-DIGIT-CSIRC/sysdiagnose#11]
TBD if we want to use python's logger. That's a clearer way to separate log messages from print messages.. Related to #10 however, since the logger prefers late bindings and not f-strings.

**Comment by cvandeplas** [comment]
And allow the user to stdout (by default), or save to a log using a cmd parameter.

**Comment by dario-br** [comment]
@cvandeplas I did a first print replacement in the commit above. But now we need to change a couple of things, that I think they deserve discussion.

1. All Parsers and Analysers must hold in the _result variable a dict and not also a list. And that dict must have a section/field named 'errors', as it already happens with some analysers. Why? Because we need to return an OK, NOK as a result of the operation. That should impact the methods parse and analyse of the Sysdiagnose class.
2. Edit the main (CLI) function to (a) log those results and (b) configure the logging (for example, a file per case, per execution). All this subject to the cmd parameter.

**Comment by dario-br** [comment]
I reverted a bit the mechanism suggested by @cvandeplas : it logs by default to jsonl (still breaks with double quotes) to any detail (INFO level), but it only logs to Console to the level defined by the cmd parameter.

Why? Because it behaves in the exact same way than parsers and analysers and because if there are long running parsing/analysing executions, you may want to see the details in a file on later stage (automation [wink]). However, unlike parsers and analysers that they only keep the last execution output, a new JSONL file is generated with every new execution.
